chore: throw on error

diff --git a/.github/workflows/dev.yaml b/.github/workflows/dev.yaml
--- a/.github/workflows/dev.yaml
+++ b/.github/workflows/dev.yaml
@@ -35,4 +35,4 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: check exceeds
         run: |
-          echo '${{ steps.loc.outputs.report }}' | grep -q 'exceeds' && echo 'Error: Limit exceeds' && exit 1
+          echo "${{ steps.loc.outputs.report }}" | grep -q 'exceeds' && echo 'Error: Limit exceeds' && exit 1
